version: "3"

services:
  redis:
    image: redis
    command: redis-server --requirepass SUASENHA --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/duducp/Redis:/var/lib/postgresql/data
  db:
    stdin_open: true
    tty: true
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/root/db/
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

